[build]
  command = "npm install -g @mermaid-js/mermaid-cli && npm run build"
  publish = "output"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-functions" 