[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "notesbylex-notebook-html"
version = "0.1.1"
description = "Save model-generated HTML and display it in Markdown Notebook or Jupyter."
readme = "README.md"
requires-python = ">=3.10"

[tool.hatch.build.targets.wheel]
packages = ["src/notebook_html"]
